package inf;

import java.util.Scanner;

public class Inf {

    public static void main(String[] args) {
        Scanner dex=new Scanner(System.in);
        int poke;
        String x;
        do { 
        System.out.print("Ingrese el numero del pokemon hasta la 3 Gen(1-386): ");
        poke = dex.nextInt();
        switch (poke) {
            case 1 -> System.out.print("Bulbasaur, numero 1, Tipo Planta, Tipo Veneno, hp: 45, ataque: 49, defensa: 49\n");
            case 2 -> System.out.print("Ivysaur, numero 2, Tipo Planta, Tipo Veneno, hp: 60, ataque: 62, defensa: 63\n");
            case 3 -> System.out.print("Venusaur, numero 3, Tipo Planta, Tipo Veneno, hp: 80, ataque: 82, defensa: 83\n");
            case 4 -> System.out.print("Charmander, numero 4, Tipo Fuego, , hp: 39, ataque: 52, defensa: 43\n");
            case 5 -> System.out.print("Charmeleon, numero 5, Tipo Fuego, , hp: 58, ataque: 64, defensa: 58\n");
            case 6 -> System.out.print("Charizard, numero 6, Tipo Fuego, Tipo Volador, hp: 78, ataque: 84, defensa: 78\n");
            case 7 -> System.out.print("Squirtle, numero 7, Tipo Agua, , hp: 44, ataque: 48, defensa: 65\n");
            case 8 -> System.out.print("Wartortle, numero 8, Tipo Agua, , hp: 59, ataque: 63, defensa: 80\n");
            case 9 -> System.out.print("Blastoise, numero 9, Tipo Agua, , hp: 79, ataque: 83, defensa: 100\n");
            case 10 -> System.out.print("Caterpie, numero 10, Tipo Bicho, , hp: 45, ataque: 30, defensa: 35\n");
            case 11 -> System.out.print("Metapod, numero 11, Tipo Bicho, , hp: 50, ataque: 20, defensa: 55\n");
            case 12 -> System.out.print("Butterfree, numero 12, Tipo Bicho, Tipo Volador, hp: 60, ataque: 45, defensa: 50\n");
            case 13 -> System.out.print("Weedle, numero 13, Tipo Bicho, Tipo Veneno, hp: 40, ataque: 35, defensa: 30\n");
            case 14 -> System.out.print("Kakuna, numero 14, Tipo Bicho, Tipo Veneno, hp: 45, ataque: 25, defensa: 50\n");
            case 15 -> System.out.print("Beedrill, numero 15, Tipo Bicho, Tipo Veneno, hp: 65, ataque: 90, defensa: 40\n");
            case 16 -> System.out.print("Pidgey, numero 16, Tipo Normal, Tipo Volador, hp: 40, ataque: 45, defensa: 40\n");
            case 17 -> System.out.print("Pidgeotto, numero 17, Tipo Normal, Tipo Volador, hp: 63, ataque: 60, defensa: 55\n");
            case 18 -> System.out.print("Pidgeot, numero 18, Tipo Normal, Tipo Volador, hp: 83, ataque: 80, defensa: 75\n");
            case 19 -> System.out.print("Rattata, numero 19, Tipo Normal, , hp: 30, ataque: 56, defensa: 35\n");
            case 20 -> System.out.print("Raticate, numero 20, Tipo Normal, , hp: 55, ataque: 81, defensa: 60\n");
            case 21 -> System.out.print("Spearow, numero 21, Tipo Normal, Tipo Volador, hp: 40, ataque: 60, defensa: 30\n");
            case 22 -> System.out.print("Fearow, numero 22, Tipo Normal, Tipo Volador, hp: 65, ataque: 90, defensa: 65\n");
            case 23 -> System.out.print("Ekans, numero 23, Tipo Veneno, , hp: 35, ataque: 60, defensa: 44\n");
            case 24 -> System.out.print("Arbok, numero 24, Tipo Veneno, , hp: 60, ataque: 85, defensa: 69\n");
            case 25 -> System.out.print("Pikachu, numero 25, Tipo Eléctrico, , hp: 35, ataque: 55, defensa: 40\n");
            case 26 -> System.out.print("Raichu, numero 26, Tipo Eléctrico, , hp: 60, ataque: 90, defensa: 55\n");
            case 27 -> System.out.print("Sandshrew, numero 27, Tipo Tierra, , hp: 50, ataque: 75, defensa: 85\n");
            case 28 -> System.out.print("Sandslash, numero 28, Tipo Tierra, , hp: 75, ataque: 100, defensa: 110\n");
            case 29 -> System.out.print("Nidoran♀, numero 29, Tipo Veneno, , hp: 55, ataque: 47, defensa: 52\n");
            case 30 -> System.out.print("Nidorina, numero 30, Tipo Veneno, , hp: 70, ataque: 62, defensa: 67\n");
            case 31 -> System.out.print("Nidoqueen, numero 31, Tipo Veneno, Tipo Tierra, hp: 90, ataque: 92, defensa: 87\n");
            case 32 -> System.out.print("Nidoran♂, numero 32, Tipo Veneno, , hp: 46, ataque: 57, defensa: 40\n");
            case 33 -> System.out.print("Nidorino, numero 33, Tipo Veneno, , hp: 61, ataque: 72, defensa: 57\n");
            case 34 -> System.out.print("Nidoking, numero 34, Tipo Veneno, Tipo Tierra, hp: 81, ataque: 102, defensa: 77\n");
            case 35 -> System.out.print("Clefairy, numero 35, Tipo Hada, , hp: 70, ataque: 45, defensa: 48\n");
            case 36 -> System.out.print("Clefable, numero 36, Tipo Hada, , hp: 95, ataque: 70, defensa: 73\n");
            case 37 -> System.out.print("Vulpix, numero 37, Tipo Fuego, , hp: 38, ataque: 41, defensa: 40\n");
            case 38 -> System.out.print("Ninetales, numero 38, Tipo Fuego, , hp: 73, ataque: 76, defensa: 75\n");
            case 39 -> System.out.print("Jigglypuff, numero 39, Tipo Normal, Tipo Hada, hp: 115, ataque: 45, defensa: 20\n");
            case 40 -> System.out.print("Wigglytuff, numero 40, Tipo Normal, Tipo Hada, hp: 140, ataque: 70, defensa: 45\n");
            case 41 -> System.out.print("Zubat, numero 41, Tipo Veneno, Tipo Volador, hp: 40, ataque: 45, defensa: 35\n");
            case 42 -> System.out.print("Golbat, numero 42, Tipo Veneno, Tipo Volador, hp: 75, ataque: 80, defensa: 70\n");
            case 43 -> System.out.print("Oddish, numero 43, Tipo Planta, Tipo Veneno, hp: 45, ataque: 50, defensa: 55\n");
            case 44 -> System.out.print("Gloom, numero 44, Tipo Planta, Tipo Veneno, hp: 60, ataque: 65, defensa: 70\n");
            case 45 -> System.out.print("Vileplume, numero 45, Tipo Planta, Tipo Veneno, hp: 75, ataque: 80, defensa: 85\n");
            case 46 -> System.out.print("Paras, numero 46, Tipo Bicho, Tipo Planta, hp: 35, ataque: 70, defensa: 55\n");
            case 47 -> System.out.print("Parasect, numero 47, Tipo Bicho, Tipo Planta, hp: 60, ataque: 95, defensa: 80\n");
            case 48 -> System.out.print("Venonat, numero 48, Tipo Bicho, Tipo Veneno, hp: 60, ataque: 55, defensa: 50\n");
            case 49 -> System.out.print("Venomoth, numero 49, Tipo Bicho, Tipo Veneno, hp: 70, ataque: 65, defensa: 60\n");
            case 50 -> System.out.print("Diglett, numero 50, Tipo Tierra, , hp: 10, ataque: 55, defensa: 25\n");
            case 51 -> System.out.print("Dugtrio, numero 51, Tipo Tierra, , hp: 35, ataque: 80, defensa: 50\n");
            case 52 -> System.out.print("Meowth, numero 52, Tipo Normal, , hp: 40, ataque: 45, defensa: 35\n");
            case 53 -> System.out.print("Persian, numero 53, Tipo Normal, , hp: 65, ataque: 70, defensa: 60\n");
            case 54 -> System.out.print("Psyduck, numero 54, Tipo Agua, , hp: 50, ataque: 52, defensa: 48\n");
            case 55 -> System.out.print("Golduck, numero 55, Tipo Agua, , hp: 80, ataque: 82, defensa: 78\n");
            case 56 -> System.out.print("Mankey, numero 56, Tipo Lucha, , hp: 40, ataque: 80, defensa: 35\n");
            case 57 -> System.out.print("Primeape, numero 57, Tipo Lucha, , hp: 65, ataque: 105, defensa: 60\n");
            case 58 -> System.out.print("Growlithe, numero 58, Tipo Fuego, , hp: 55, ataque: 70, defensa: 45\n");
            case 59 -> System.out.print("Arcanine, numero 59, Tipo Fuego, , hp: 90, ataque: 110, defensa: 80\n");
            case 60 -> System.out.print("Poliwag, numero 60, Tipo Agua, , hp: 40, ataque: 50, defensa: 40\n");
            case 61 -> System.out.print("Poliwhirl, numero 61, Tipo Agua, , hp: 65, ataque: 65, defensa: 65\n");
            case 62 -> System.out.print("Poliwrath, numero 62, Tipo Agua, Tipo Lucha, hp: 90, ataque: 95, defensa: 95\n");
            case 63 -> System.out.print("Abra, numero 63, Tipo Psíquico, , hp: 25, ataque: 20, defensa: 15\n");
            case 64 -> System.out.print("Kadabra, numero 64, Tipo Psíquico, , hp: 40, ataque: 35, defensa: 30\n");
            case 65 -> System.out.print("Alakazam, numero 65, Tipo Psíquico, , hp: 55, ataque: 50, defensa: 45\n");
            case 66 -> System.out.print("Machop, numero 66, Tipo Lucha, , hp: 70, ataque: 80, defensa: 50\n");
            case 67 -> System.out.print("Machoke, numero 67, Tipo Lucha, , hp: 80, ataque: 100, defensa: 70\n");
            case 68 -> System.out.print("Machamp, numero 68, Tipo Lucha, , hp: 90, ataque: 130, defensa: 80\n");
            case 69 -> System.out.print("Bellsprout, numero 69, Tipo Planta, Tipo Veneno, hp: 50, ataque: 75, defensa: 35\n");
            case 70 -> System.out.print("Weepinbell, numero 70, Tipo Planta, Tipo Veneno, hp: 65, ataque: 90, defensa: 50\n");
            case 71 -> System.out.print("Victreebel, numero 71, Tipo Planta, Tipo Veneno, hp: 80, ataque: 105, defensa: 65\n");
            case 72 -> System.out.print("Tentacool, numero 72, Tipo Agua, Tipo Veneno, hp: 40, ataque: 40, defensa: 35\n");
            case 73 -> System.out.print("Tentacruel, numero 73, Tipo Agua, Tipo Veneno, hp: 80, ataque: 70, defensa: 65\n");
            case 74 -> System.out.print("Geodude, numero 74, Tipo Roca, Tipo Tierra, hp: 40, ataque: 80, defensa: 100\n");
            case 75 -> System.out.print("Graveler, numero 75, Tipo Roca, Tipo Tierra, hp: 55, ataque: 95, defensa: 115\n");
            case 76 -> System.out.print("Golem, numero 76, Tipo Roca, Tipo Tierra, hp: 80, ataque: 120, defensa: 130\n");
            case 77 -> System.out.print("Ponyta, numero 77, Tipo Fuego, , hp: 50, ataque: 85, defensa: 55\n");
            case 78 -> System.out.print("Rapidash, numero 78, Tipo Fuego, , hp: 65, ataque: 100, defensa: 70\n");
            case 79 -> System.out.print("Slowpoke, numero 79, Tipo Agua, Tipo Psíquico, hp: 90, ataque: 65, defensa: 65\n");
            case 80 -> System.out.print("Slowbro, numero 80, Tipo Agua, Tipo Psíquico, hp: 95, ataque: 75, defensa: 110\n");
            case 81 -> System.out.print("Magnemite, numero 81, Tipo Eléctrico, Tipo Acero, hp: 25, ataque: 35, defensa: 70\n");
            case 82 -> System.out.print("Magneton, numero 82, Tipo Eléctrico, Tipo Acero, hp: 50, ataque: 60, defensa: 95\n");
            case 83 -> System.out.print("Farfetch'd, numero 83, Tipo Normal, Tipo Volador, hp: 52, ataque: 65, defensa: 55\n");
            case 84 -> System.out.print("Doduo, numero 84, Tipo Normal, Tipo Volador, hp: 35, ataque: 85, defensa: 45\n");
            case 85 -> System.out.print("Dodrio, numero 85, Tipo Normal, Tipo Volador, hp: 60, ataque: 110, defensa: 70\n");
            case 86 -> System.out.print("Seel, numero 86, Tipo Agua, , hp: 65, ataque: 45, defensa: 55\n");
            case 87 -> System.out.print("Dewgong, numero 87, Tipo Agua, Tipo Hielo, hp: 90, ataque: 70, defensa: 80\n");
            case 88 -> System.out.print("Grimer, numero 88, Tipo Veneno, , hp: 80, ataque: 80, defensa: 50\n");
            case 89 -> System.out.print("Muk, numero 89, Tipo Veneno, , hp: 105, ataque: 105, defensa: 75\n");
            case 90 -> System.out.print("Shellder, numero 90, Tipo Agua, , hp: 30, ataque: 65, defensa: 100\n");
            case 91 -> System.out.print("Cloyster, numero 91, Tipo Agua, Tipo Hielo, hp: 50, ataque: 95, defensa: 180\n");
            case 92 -> System.out.print("Gastly, numero 92, Tipo Fantasma, Tipo Veneno, hp: 30, ataque: 35, defensa: 30\n");
            case 93 -> System.out.print("Haunter, numero 93, Tipo Fantasma, Tipo Veneno, hp: 45, ataque: 50, defensa: 45\n");
            case 94 -> System.out.print("Gengar, numero 94, Tipo Fantasma, Tipo Veneno, hp: 60, ataque: 65, defensa: 60\n");
            case 95 -> System.out.print("Onix, numero 95, Tipo Roca, Tipo Tierra, hp: 35, ataque: 45, defensa: 160\n");
            case 96 -> System.out.print("Drowzee, numero 96, Tipo Psíquico, , hp: 60, ataque: 48, defensa: 45\n");
            case 97 -> System.out.print("Hypno, numero 97, Tipo Psíquico, , hp: 85, ataque: 73, defensa: 70\n");
            case 98 -> System.out.print("Krabby, numero 98, Tipo Agua, , hp: 30, ataque: 105, defensa: 90\n");
            case 99 -> System.out.print("Kingler, numero 99, Tipo Agua, , hp: 55, ataque: 130, defensa: 115\n");
            case 100 -> System.out.print("Voltorb, numero 100, Tipo Eléctrico, , hp: 40, ataque: 30, defensa: 50\n");
            case 101 -> System.out.print("Electrode, numero 101, Tipo Eléctrico, , hp: 60, ataque: 50, defensa: 70\n");
            case 102 -> System.out.print("Exeggcute, numero 102, Tipo Planta, Tipo Psíquico, hp: 60, ataque: 40, defensa: 80\n");
            case 103 -> System.out.print("Exeggutor, numero 103, Tipo Planta, Tipo Psíquico, hp: 95, ataque: 95, defensa: 85\n");
            case 104 -> System.out.print("Cubone, numero 104, Tipo Tierra, , hp: 50, ataque: 50, defensa: 95\n");
            case 105 -> System.out.print("Marowak, numero 105, Tipo Tierra, , hp: 60, ataque: 80, defensa: 110\n");
            case 106 -> System.out.print("Hitmonlee, numero 106, Tipo Lucha, , hp: 50, ataque: 120, defensa: 53\n");
            case 107 -> System.out.print("Hitmonchan, numero 107, Tipo Lucha, , hp: 50, ataque: 105, defensa: 79\n");
            case 108 -> System.out.print("Lickitung, numero 108, Tipo Normal, , hp: 90, ataque: 55, defensa: 75\n");
            case 109 -> System.out.print("Koffing, numero 109, Tipo Veneno, , hp: 40, ataque: 65, defensa: 95\n");
            case 110 -> System.out.print("Weezing, numero 110, Tipo Veneno, , hp: 65, ataque: 90, defensa: 120\n");
            case 111 -> System.out.print("Rhyhorn, numero 111, Tipo Tierra, Tipo Roca, hp: 80, ataque: 85, defensa: 95\n");
            case 112 -> System.out.print("Rhydon, numero 112, Tipo Tierra, Tipo Roca, hp: 105, ataque: 130, defensa: 120\n");
            case 113 -> System.out.print("Chansey, numero 113, Tipo Normal, , hp: 250, ataque: 5, defensa: 5\n");
            case 114 -> System.out.print("Tangela, numero 114, Tipo Planta, , hp: 65, ataque: 55, defensa: 115\n");
            case 115 -> System.out.print("Kangaskhan, numero 115, Tipo Normal, , hp: 105, ataque: 95, defensa: 80\n");
            case 116 -> System.out.print("Horsea, numero 116, Tipo Agua, , hp: 30, ataque: 40, defensa: 70\n");
            case 117 -> System.out.print("Seadra, numero 117, Tipo Agua, , hp: 55, ataque: 65, defensa: 95\n");
            case 118 -> System.out.print("Goldeen, numero 118, Tipo Agua, , hp: 45, ataque: 67, defensa: 60\n");
            case 119 -> System.out.print("Seaking, numero 119, Tipo Agua, , hp: 80, ataque: 92, defensa: 65\n");
            case 120 -> System.out.print("Staryu, numero 120, Tipo Agua, , hp: 30, ataque: 45, defensa: 55\n");
            case 121 -> System.out.print("Starmie, numero 121, Tipo Agua, Tipo Psíquico, hp: 60, ataque: 75, defensa: 85\n");
            case 122 -> System.out.print("Mr. Mime, numero 122, Tipo Psíquico, Tipo Hada, hp: 40, ataque: 45, defensa: 65\n");
            case 123 -> System.out.print("Scyther, numero 123, Tipo Bicho, Tipo Volador, hp: 70, ataque: 110, defensa: 80\n");
            case 124 -> System.out.print("Jynx, numero 124, Tipo Hielo, Tipo Psíquico, hp: 65, ataque: 50, defensa: 35\n");
            case 125 -> System.out.print("Electabuzz, numero 125, Tipo Eléctrico, , hp: 65, ataque: 83, defensa: 57\n");
            case 126 -> System.out.print("Magmar, numero 126, Tipo Fuego, , hp: 65, ataque: 95, defensa: 57\n");
            case 127 -> System.out.print("Pinsir, numero 127, Tipo Bicho, , hp: 65, ataque: 125, defensa: 100\n");
            case 128 -> System.out.print("Tauros, numero 128, Tipo Normal, , hp: 75, ataque: 100, defensa: 95\n");
            case 129 -> System.out.print("Magikarp, numero 129, Tipo Agua, , hp: 20, ataque: 10, defensa: 55\n");
            case 130 -> System.out.print("Gyarados, numero 130, Tipo Agua, Tipo Volador, hp: 95, ataque: 125, defensa: 79\n");
            case 131 -> System.out.print("Lapras, numero 131, Tipo Agua, Tipo Hielo, hp: 130, ataque: 85, defensa: 80\n");
            case 132 -> System.out.print("Ditto, numero 132, Tipo Normal, , hp: 48, ataque: 48, defensa: 48\n");
            case 133 -> System.out.print("Eevee, numero 133, Tipo Normal, , hp: 55, ataque: 55, defensa: 50\n");
            case 134 -> System.out.print("Vaporeon, numero 134, Tipo Agua, , hp: 130, ataque: 65, defensa: 60\n");
            case 135 -> System.out.print("Jolteon, numero 135, Tipo Eléctrico, , hp: 65, ataque: 65, defensa: 60\n");
            case 136 -> System.out.print("Flareon, numero 136, Tipo Fuego, , hp: 65, ataque: 130, defensa: 60\n");
            case 137 -> System.out.print("Porygon, numero 137, Tipo Normal, , hp: 65, ataque: 60, defensa: 70\n");
            case 138 -> System.out.print("Omanyte, numero 138, Tipo Roca, Tipo Agua, hp: 35, ataque: 40, defensa: 100\n");
            case 139 -> System.out.print("Omastar, numero 139, Tipo Roca, Tipo Agua, hp: 70, ataque: 60, defensa: 125\n");
            case 140 -> System.out.print("Kabuto, numero 140, Tipo Roca, Tipo Agua, hp: 30, ataque: 80, defensa: 90\n");
            case 141 -> System.out.print("Kabutops, numero 141, Tipo Roca, Tipo Agua, hp: 60, ataque: 115, defensa: 105\n");
            case 142 -> System.out.print("Aerodactyl, numero 142, Tipo Roca, Tipo Volador, hp: 80, ataque: 105, defensa: 65\n");
            case 143 -> System.out.print("Snorlax, numero 143, Tipo Normal, , hp: 160, ataque: 110, defensa: 65\n");
            case 144 -> System.out.print("Articuno, numero 144, Tipo Hielo, Tipo Volador, hp: 90, ataque: 85, defensa: 100\n");
            case 145 -> System.out.print("Zapdos, numero 145, Tipo Eléctrico, Tipo Volador, hp: 90, ataque: 90, defensa: 85\n");
            case 146 -> System.out.print("Moltres, numero 146, Tipo Fuego, Tipo Volador, hp: 90, ataque: 100, defensa: 90\n");
            case 147 -> System.out.print("Dratini, numero 147, Tipo Dragón, , hp: 41, ataque: 64, defensa: 45\n");
            case 148 -> System.out.print("Dragonair, numero 148, Tipo Dragón, , hp: 61, ataque: 84, defensa: 65\n");
            case 149 -> System.out.print("Dragonite, numero 149, Tipo Dragón, Tipo Volador, hp: 91, ataque: 134, defensa: 95\n");
            case 150 -> System.out.print("Mewtwo, numero 150, Tipo Psíquico, , hp: 106, ataque: 110, defensa: 90\n");
            case 151 -> System.out.print("Mew, numero 151, Tipo Psíquico, , hp: 100, ataque: 100, defensa: 100\n");
            case 152 -> System.out.print("Chikorita, numero 152, Tipo Planta, , hp: 45, ataque: 49, defensa: 65\n");
            case 153 -> System.out.print("Bayleef, numero 153, Tipo Planta, , hp: 60, ataque: 62, defensa: 80\n");
            case 154 -> System.out.print("Meganium, numero 154, Tipo Planta, , hp: 80, ataque: 82, defensa: 100\n");
            case 155 -> System.out.print("Cyndaquil, numero 155, Tipo Fuego, , hp: 39, ataque: 52, defensa: 43\n");
            case 156 -> System.out.print("Quilava, numero 156, Tipo Fuego, , hp: 58, ataque: 64, defensa: 58\n");
            case 157 -> System.out.print("Typhlosion, numero 157, Tipo Fuego, , hp: 78, ataque: 84, defensa: 78\n");
            case 158 -> System.out.print("Totodile, numero 158, Tipo Agua, , hp: 50, ataque: 65, defensa: 64\n");
            case 159 -> System.out.print("Croconaw, numero 159, Tipo Agua, , hp: 65, ataque: 80, defensa: 80\n");
            case 160 -> System.out.print("Feraligatr, numero 160, Tipo Agua, , hp: 85, ataque: 105, defensa: 100\n");
            case 161 -> System.out.print("Sentret, numero 161, Tipo Normal, , hp: 35, ataque: 46, defensa: 34\n");
            case 162 -> System.out.print("Furret, numero 162, Tipo Normal, , hp: 85, ataque: 76, defensa: 64\n");
            case 163 -> System.out.print("Hoothoot, numero 163, Tipo Normal, Tipo Volador, hp: 60, ataque: 30, defensa: 30\n");
            case 164 -> System.out.print("Noctowl, numero 164, Tipo Normal, Tipo Volador, hp: 100, ataque: 50, defensa: 50\n");
            case 165 -> System.out.print("Ledyba, numero 165, Tipo Bicho, Tipo Volador, hp: 40, ataque: 20, defensa: 30\n");
            case 166 -> System.out.print("Ledian, numero 166, Tipo Bicho, Tipo Volador, hp: 55, ataque: 35, defensa: 50\n");
            case 167 -> System.out.print("Spinarak, numero 167, Tipo Bicho, Tipo Veneno, hp: 40, ataque: 60, defensa: 40\n");
            case 168 -> System.out.print("Ariados, numero 168, Tipo Bicho, Tipo Veneno, hp: 70, ataque: 90, defensa: 70\n");
            case 169 -> System.out.print("Crobat, numero 169, Tipo Veneno, Tipo Volador, hp: 85, ataque: 90, defensa: 80\n");
            case 170 -> System.out.print("Chinchou, numero 170, Tipo Agua, Tipo Eléctrico, hp: 75, ataque: 38, defensa: 38\n");
            case 171 -> System.out.print("Lanturn, numero 171, Tipo Agua, Tipo Eléctrico, hp: 125, ataque: 58, defensa: 58\n");
            case 172 -> System.out.print("Pichu, numero 172, Tipo Eléctrico, , hp: 20, ataque: 40, defensa: 15\n");
            case 173 -> System.out.print("Cleffa, numero 173, Tipo Hada, , hp: 50, ataque: 25, defensa: 28\n");
            case 174 -> System.out.print("Igglybuff, numero 174, Tipo Normal, Tipo Hada, hp: 90, ataque: 30, defensa: 15\n");
            case 175 -> System.out.print("Togepi, numero 175, Tipo Hada, , hp: 35, ataque: 20, defensa: 65\n");
            case 176 -> System.out.print("Togetic, numero 176, Tipo Hada, Tipo Volador, hp: 55, ataque: 40, defensa: 85\n");
            case 177 -> System.out.print("Natu, numero 177, Tipo Psíquico, Tipo Volador, hp: 40, ataque: 50, defensa: 45\n");
            case 178 -> System.out.print("Xatu, numero 178, Tipo Psíquico, Tipo Volador, hp: 65, ataque: 75, defensa: 70\n");
            case 179 -> System.out.print("Mareep, numero 179, Tipo Eléctrico, , hp: 55, ataque: 40, defensa: 40\n");
            case 180 -> System.out.print("Flaaffy, numero 180, Tipo Eléctrico, , hp: 70, ataque: 55, defensa: 55\n");
            case 181 -> System.out.print("Ampharos, numero 181, Tipo Eléctrico, , hp: 90, ataque: 75, defensa: 85\n");
            case 182 -> System.out.print("Bellossom, numero 182, Tipo Planta, , hp: 75, ataque: 80, defensa: 85\n");
            case 183 -> System.out.print("Marill, numero 183, Tipo Agua, Tipo Hada, hp: 70, ataque: 20, defensa: 50\n");
            case 184 -> System.out.print("Azumarill, numero 184, Tipo Agua, Tipo Hada, hp: 100, ataque: 50, defensa: 80\n");
            case 185 -> System.out.print("Sudowoodo, numero 185, Tipo Roca, , hp: 70, ataque: 100, defensa: 115\n");
            case 186 -> System.out.print("Politoed, numero 186, Tipo Agua, , hp: 90, ataque: 75, defensa: 75\n");
            case 187 -> System.out.print("Hoppip, numero 187, Tipo Planta, Tipo Volador, hp: 35, ataque: 35, defensa: 40\n");
            case 188 -> System.out.print("Skiploom, numero 188, Tipo Planta, Tipo Volador, hp: 55, ataque: 45, defensa: 50\n");
            case 189 -> System.out.print("Jumpluff, numero 189, Tipo Planta, Tipo Volador, hp: 75, ataque: 55, defensa: 70\n");
            case 190 -> System.out.print("Aipom, numero 190, Tipo Normal, , hp: 55, ataque: 70, defensa: 55\n");
            case 191 -> System.out.print("Sunkern, numero 191, Tipo Planta, , hp: 30, ataque: 30, defensa: 30\n");
            case 192 -> System.out.print("Sunflora, numero 192, Tipo Planta, , hp: 75, ataque: 75, defensa: 55\n");
            case 193 -> System.out.print("Yanma, numero 193, Tipo Bicho, Tipo Volador, hp: 65, ataque: 65, defensa: 45\n");
            case 194 -> System.out.print("Wooper, numero 194, Tipo Agua, Tipo Tierra, hp: 55, ataque: 45, defensa: 45\n");
            case 195 -> System.out.print("Quagsire, numero 195, Tipo Agua, Tipo Tierra, hp: 95, ataque: 85, defensa: 85\n");
            case 196 -> System.out.print("Espeon, numero 196, Tipo Psíquico, , hp: 65, ataque: 65, defensa: 60\n");
            case 197 -> System.out.print("Umbreon, numero 197, Tipo Siniestro, , hp: 95, ataque: 65, defensa: 110\n");
            case 198 -> System.out.print("Murkrow, numero 198, Tipo Siniestro, Tipo Volador, hp: 60, ataque: 85, defensa: 42\n");
            case 199 -> System.out.print("Slowking, numero 199, Tipo Agua, Tipo Psíquico, hp: 95, ataque: 75, defensa: 80\n");
            case 200 -> System.out.print("Misdreavus, numero 200, Tipo Fantasma, , hp: 60, ataque: 60, defensa: 60\n");
            case 201 -> System.out.print("Unown, numero 201, Tipo Psíquico, , hp: 48, ataque: 72, defensa: 48\n");
            case 202 -> System.out.print("Wobbuffet, numero 202, Tipo Psíquico, , hp: 190, ataque: 33, defensa: 58\n");
            case 203 -> System.out.print("Girafarig, numero 203, Tipo Normal, Tipo Psíquico, hp: 70, ataque: 80, defensa: 65\n");
            case 204 -> System.out.print("Pineco, numero 204, Tipo Bicho, , hp: 50, ataque: 65, defensa: 90\n");
            case 205 -> System.out.print("Forretress, numero 205, Tipo Bicho, Tipo Acero, hp: 75, ataque: 90, defensa: 140\n");
            case 206 -> System.out.print("Dunsparce, numero 206, Tipo Normal, , hp: 100, ataque: 70, defensa: 70\n");
            case 207 -> System.out.print("Gligar, numero 207, Tipo Tierra, Tipo Volador, hp: 65, ataque: 75, defensa: 105\n");
            case 208 -> System.out.print("Steelix, numero 208, Tipo Acero, Tipo Tierra, hp: 75, ataque: 85, defensa: 200\n");
            case 209 -> System.out.print("Snubbull, numero 209, Tipo Hada, , hp: 60, ataque: 80, defensa: 50\n");
            case 210 -> System.out.print("Granbull, numero 210, Tipo Hada, , hp: 90, ataque: 120, defensa: 75\n");
            case 211 -> System.out.print("Qwilfish, numero 211, Tipo Agua, Tipo Veneno, hp: 65, ataque: 95, defensa: 85\n");
            case 212 -> System.out.print("Scizor, numero 212, Tipo Bicho, Tipo Acero, hp: 70, ataque: 130, defensa: 100\n");
            case 213 -> System.out.print("Shuckle, numero 213, Tipo Bicho, Tipo Roca, hp: 20, ataque: 10, defensa: 230\n");
            case 214 -> System.out.print("Heracross, numero 214, Tipo Bicho, Tipo Lucha, hp: 80, ataque: 125, defensa: 75\n");
            case 215 -> System.out.print("Sneasel, numero 215, Tipo Siniestro, Tipo Hielo, hp: 55, ataque: 95, defensa: 55\n");
            case 216 -> System.out.print("Teddiursa, numero 216, Tipo Normal, , hp: 60, ataque: 80, defensa: 50\n");
            case 217 -> System.out.print("Ursaring, numero 217, Tipo Normal, , hp: 90, ataque: 130, defensa: 75\n");
            case 218 -> System.out.print("Slugma, numero 218, Tipo Fuego, , hp: 40, ataque: 40, defensa: 40\n");
            case 219 -> System.out.print("Magcargo, numero 219, Tipo Fuego, Tipo Roca, hp: 50, ataque: 50, defensa: 120\n");
            case 220 -> System.out.print("Swinub, numero 220, Tipo Hielo, Tipo Tierra, hp: 50, ataque: 50, defensa: 40\n");
            case 221 -> System.out.print("Piloswine, numero 221, Tipo Hielo, Tipo Tierra, hp: 100, ataque: 100, defensa: 80\n");
            case 222 -> System.out.print("Corsola, numero 222, Tipo Agua, Tipo Roca, hp: 65, ataque: 55, defensa: 95\n");
            case 223 -> System.out.print("Remoraid, numero 223, Tipo Agua, , hp: 35, ataque: 65, defensa: 35\n");
            case 224 -> System.out.print("Octillery, numero 224, Tipo Agua, , hp: 75, ataque: 105, defensa: 75\n");
            case 225 -> System.out.print("Delibird, numero 225, Tipo Hielo, Tipo Volador, hp: 45, ataque: 55, defensa: 45\n");
            case 226 -> System.out.print("Mantine, numero 226, Tipo Agua, Tipo Volador, hp: 85, ataque: 40, defensa: 70\n");
            case 227 -> System.out.print("Skarmory, numero 227, Tipo Acero, Tipo Volador, hp: 65, ataque: 80, defensa: 140\n");
            case 228 -> System.out.print("Houndour, numero 228, Tipo Siniestro, Tipo Fuego, hp: 45, ataque: 60, defensa: 30\n");
            case 229 -> System.out.print("Houndoom, numero 229, Tipo Siniestro, Tipo Fuego, hp: 75, ataque: 90, defensa: 50\n");
            case 230 -> System.out.print("Kingdra, numero 230, Tipo Agua, Tipo Dragón, hp: 75, ataque: 95, defensa: 95\n");
            case 231 -> System.out.print("Phanpy, numero 231, Tipo Tierra, , hp: 90, ataque: 60, defensa: 60\n");
            case 232 -> System.out.print("Donphan, numero 232, Tipo Tierra, , hp: 90, ataque: 120, defensa: 120\n");
            case 233 -> System.out.print("Porygon2, numero 233, Tipo Normal, , hp: 85, ataque: 80, defensa: 90\n");
            case 234 -> System.out.print("Stantler, numero 234, Tipo Normal, , hp: 73, ataque: 95, defensa: 62\n");
            case 235 -> System.out.print("Smeargle, numero 235, Tipo Normal, , hp: 55, ataque: 20, defensa: 35\n");
            case 236 -> System.out.print("Tyrogue, numero 236, Tipo Lucha, , hp: 35, ataque: 35, defensa: 35\n");
            case 237 -> System.out.print("Hitmontop, numero 237, Tipo Lucha, , hp: 50, ataque: 95, defensa: 95\n");
            case 238 -> System.out.print("Smoochum, numero 238, Tipo Hielo, Tipo Psíquico, hp: 45, ataque: 30, defensa: 15\n");
            case 239 -> System.out.print("Elekid, numero 239, Tipo Eléctrico, , hp: 45, ataque: 63, defensa: 37\n");
            case 240 -> System.out.print("Magby, numero 240, Tipo Fuego, , hp: 45, ataque: 75, defensa: 37\n");
            case 241 -> System.out.print("Miltank, numero 241, Tipo Normal, , hp: 95, ataque: 80, defensa: 105\n");
            case 242 -> System.out.print("Blissey, numero 242, Tipo Normal, , hp: 255, ataque: 10, defensa: 10\n");
            case 243 -> System.out.print("Raikou, numero 243, Tipo Eléctrico, , hp: 90, ataque: 85, defensa: 75\n");
            case 244 -> System.out.print("Entei, numero 244, Tipo Fuego, , hp: 115, ataque: 115, defensa: 85\n");
            case 245 -> System.out.print("Suicune, numero 245, Tipo Agua, , hp: 100, ataque: 75, defensa: 115\n");
            case 246 -> System.out.print("Larvitar, numero 246, Tipo Roca, Tipo Tierra, hp: 50, ataque: 64, defensa: 50\n");
            case 247 -> System.out.print("Pupitar, numero 247, Tipo Roca, Tipo Tierra, hp: 70, ataque: 84, defensa: 70\n");
            case 248 -> System.out.print("Tyranitar, numero 248, Tipo Roca, Tipo Siniestro, hp: 100, ataque: 134, defensa: 110\n");
            case 249 -> System.out.print("Lugia, numero 249, Tipo Psíquico, Tipo Volador, hp: 106, ataque: 90, defensa: 130\n");
            case 250 -> System.out.print("Ho-oh, numero 250, Tipo Fuego, Tipo Volador, hp: 106, ataque: 130, defensa: 90\n");
            case 251 -> System.out.print("Celebi, numero 251, Tipo Psíquico, Tipo Planta, hp: 100, ataque: 100, defensa: 100\n");
            case 252 -> System.out.print("Treecko, numero 252, Tipo Planta, , hp: 40, ataque: 45, defensa: 35\n");
            case 253 -> System.out.print("Grovyle, numero 253, Tipo Planta, , hp: 50, ataque: 65, defensa: 45\n");
            case 254 -> System.out.print("Sceptile, numero 254, Tipo Planta, , hp: 70, ataque: 85, defensa: 65\n");
            case 255 -> System.out.print("Torchic, numero 255, Tipo Fuego, , hp: 45, ataque: 60, defensa: 40\n");
            case 256 -> System.out.print("Combusken, numero 256, Tipo Fuego, Tipo Lucha, hp: 60, ataque: 85, defensa: 60\n");
            case 257 -> System.out.print("Blaziken, numero 257, Tipo Fuego, Tipo Lucha, hp: 80, ataque: 120, defensa: 70\n");
            case 258 -> System.out.print("Mudkip, numero 258, Tipo Agua, , hp: 50, ataque: 70, defensa: 50\n");
            case 259 -> System.out.print("Marshtomp, numero 259, Tipo Agua, Tipo Tierra, hp: 70, ataque: 85, defensa: 70\n");
            case 260 -> System.out.print("Swampert, numero 260, Tipo Agua, Tipo Tierra, hp: 100, ataque: 110, defensa: 90\n");
            case 261 -> System.out.print("Poochyena, numero 261, Tipo Siniestro, , hp: 35, ataque: 55, defensa: 35\n");
            case 262 -> System.out.print("Mightyena, numero 262, Tipo Siniestro, , hp: 70, ataque: 90, defensa: 70\n");
            case 263 -> System.out.print("Zigzagoon, numero 263, Tipo Normal, , hp: 38, ataque: 30, defensa: 41\n");
            case 264 -> System.out.print("Linoone, numero 264, Tipo Normal, , hp: 78, ataque: 70, defensa: 61\n");
            case 265 -> System.out.print("Wurmple, numero 265, Tipo Bicho, , hp: 45, ataque: 45, defensa: 35\n");
            case 266 -> System.out.print("Silcoon, numero 266, Tipo Bicho, , hp: 50, ataque: 35, defensa: 55\n");
            case 267 -> System.out.print("Beautifly, numero 267, Tipo Bicho, Tipo Volador, hp: 60, ataque: 70, defensa: 50\n");
            case 268 -> System.out.print("Cascoon, numero 268, Tipo Bicho, , hp: 50, ataque: 35, defensa: 55\n");
            case 269 -> System.out.print("Dustox, numero 269, Tipo Bicho, Tipo Veneno, hp: 60, ataque: 50, defensa: 70\n");
            case 270 -> System.out.print("Lotad, numero 270, Tipo Agua, Tipo Planta, hp: 40, ataque: 30, defensa: 30\n");
            case 271 -> System.out.print("Lombre, numero 271, Tipo Agua, Tipo Planta, hp: 60, ataque: 50, defensa: 50\n");
            case 272 -> System.out.print("Ludicolo, numero 272, Tipo Agua, Tipo Planta, hp: 80, ataque: 70, defensa: 70\n");
            case 273 -> System.out.print("Seedot, numero 273, Tipo Planta, , hp: 40, ataque: 40, defensa: 50\n");
            case 274 -> System.out.print("Nuzleaf, numero 274, Tipo Planta, Tipo Siniestro, hp: 70, ataque: 70, defensa: 40\n");
            case 275 -> System.out.print("Shiftry, numero 275, Tipo Planta, Tipo Siniestro, hp: 90, ataque: 100, defensa: 60\n");
            case 276 -> System.out.print("Taillow, numero 276, Tipo Normal, Tipo Volador, hp: 40, ataque: 55, defensa: 30\n");
            case 277 -> System.out.print("Swellow, numero 277, Tipo Normal, Tipo Volador, hp: 60, ataque: 85, defensa: 60\n");
            case 278 -> System.out.print("Wingull, numero 278, Tipo Agua, Tipo Volador, hp: 40, ataque: 30, defensa: 30\n");
            case 279 -> System.out.print("Pelipper, numero 279, Tipo Agua, Tipo Volador, hp: 60, ataque: 50, defensa: 100\n");
            case 280 -> System.out.print("Ralts, numero 280, Tipo Psíquico, Tipo Hada, hp: 28, ataque: 25, defensa: 25\n");
            case 281 -> System.out.print("Kirlia, numero 281, Tipo Psíquico, Tipo Hada, hp: 38, ataque: 35, defensa: 35\n");
            case 282 -> System.out.print("Gardevoir, numero 282, Tipo Psíquico, Tipo Hada, hp: 68, ataque: 65, defensa: 65\n");
            case 283 -> System.out.print("Surskit, numero 283, Tipo Bicho, Tipo Agua, hp: 40, ataque: 30, defensa: 32\n");
            case 284 -> System.out.print("Masquerain, numero 284, Tipo Bicho, Tipo Volador, hp: 70, ataque: 60, defensa: 62\n");
            case 285 -> System.out.print("Shroomish, numero 285, Tipo Planta, , hp: 60, ataque: 40, defensa: 60\n");
            case 286 -> System.out.print("Breloom, numero 286, Tipo Planta, Tipo Lucha, hp: 60, ataque: 130, defensa: 80\n");
            case 287 -> System.out.print("Slakoth, numero 287, Tipo Normal, , hp: 60, ataque: 60, defensa: 60\n");
            case 288 -> System.out.print("Vigoroth, numero 288, Tipo Normal, , hp: 80, ataque: 80, defensa: 80\n");
            case 289 -> System.out.print("Slaking, numero 289, Tipo Normal, , hp: 150, ataque: 160, defensa: 100\n");
            case 290 -> System.out.print("Nincada, numero 290, Tipo Bicho, Tipo Tierra, hp: 31, ataque: 45, defensa: 90\n");
            case 291 -> System.out.print("Ninjask, numero 291, Tipo Bicho, Tipo Volador, hp: 61, ataque: 90, defensa: 45\n");
            case 292 -> System.out.print("Shedinja, numero 292, Tipo Bicho, Tipo Fantasma, hp: 1, ataque: 90, defensa: 45\n");
            case 293 -> System.out.print("Whismur, numero 293, Tipo Normal, , hp: 64, ataque: 51, defensa: 23\n");
            case 294 -> System.out.print("Loudred, numero 294, Tipo Normal, , hp: 84, ataque: 71, defensa: 43\n");
            case 295 -> System.out.print("Exploud, numero 295, Tipo Normal, , hp: 104, ataque: 91, defensa: 63\n");
            case 296 -> System.out.print("Makuhita, numero 296, Tipo Lucha, , hp: 72, ataque: 60, defensa: 30\n");
            case 297 -> System.out.print("Hariyama, numero 297, Tipo Lucha, , hp: 144, ataque: 120, defensa: 60\n");
            case 298 -> System.out.print("Azurill, numero 298, Tipo Normal, Tipo Hada, hp: 50, ataque: 20, defensa: 40\n");
            case 299 -> System.out.print("Nosepass, numero 299, Tipo Roca, , hp: 30, ataque: 45, defensa: 135\n");
            case 300 -> System.out.print("Skitty, numero 300, Tipo Normal, , hp: 50, ataque: 45, defensa: 45\n");
            case 301 -> System.out.print("Delcatty, numero 301, Tipo Normal, , hp: 70, ataque: 65, defensa: 65\n");
            case 302 -> System.out.print("Sableye, numero 302, Tipo Siniestro, Tipo Fantasma, hp: 50, ataque: 75, defensa: 75\n");
            case 303 -> System.out.print("Mawile, numero 303, Tipo Acero, Tipo Hada, hp: 50, ataque: 85, defensa: 85\n");
            case 304 -> System.out.print("Aron, numero 304, Tipo Acero, Tipo Roca, hp: 50, ataque: 70, defensa: 100\n");
            case 305 -> System.out.print("Lairon, numero 305, Tipo Acero, Tipo Roca, hp: 60, ataque: 90, defensa: 140\n");
            case 306 -> System.out.print("Aggron, numero 306, Tipo Acero, Tipo Roca, hp: 70, ataque: 110, defensa: 180\n");
            case 307 -> System.out.print("Meditite, numero 307, Tipo Lucha, Tipo Psíquico, hp: 30, ataque: 40, defensa: 55\n");
            case 308 -> System.out.print("Medicham, numero 308, Tipo Lucha, Tipo Psíquico, hp: 60, ataque: 60, defensa: 75\n");
            case 309 -> System.out.print("Electrike, numero 309, Tipo Eléctrico, , hp: 40, ataque: 45, defensa: 40\n");
            case 310 -> System.out.print("Manectric, numero 310, Tipo Eléctrico, , hp: 70, ataque: 75, defensa: 60\n");
            case 311 -> System.out.print("Plusle, numero 311, Tipo Eléctrico, , hp: 60, ataque: 50, defensa: 40\n");
            case 312 -> System.out.print("Minun, numero 312, Tipo Eléctrico, , hp: 60, ataque: 40, defensa: 50\n");
            case 313 -> System.out.print("Volbeat, numero 313, Tipo Bicho, , hp: 65, ataque: 73, defensa: 55\n");
            case 314 -> System.out.print("Illumise, numero 314, Tipo Bicho, , hp: 65, ataque: 47, defensa: 55\n");
            case 315 -> System.out.print("Roselia, numero 315, Tipo Planta, Tipo Veneno, hp: 50, ataque: 60, defensa: 45\n");
            case 316 -> System.out.print("Gulpin, numero 316, Tipo Veneno, , hp: 70, ataque: 43, defensa: 53\n");
            case 317 -> System.out.print("Swalot, numero 317, Tipo Veneno, , hp: 100, ataque: 73, defensa: 83\n");
            case 318 -> System.out.print("Carvanha, numero 318, Tipo Agua, Tipo Siniestro, hp: 45, ataque: 90, defensa: 20\n");
            case 319 -> System.out.print("Sharpedo, numero 319, Tipo Agua, Tipo Siniestro, hp: 70, ataque: 120, defensa: 40\n");
            case 320 -> System.out.print("Wailmer, numero 320, Tipo Agua, , hp: 130, ataque: 70, defensa: 35\n");
            case 321 -> System.out.print("Wailord, numero 321, Tipo Agua, , hp: 170, ataque: 90, defensa: 45\n");
            case 322 -> System.out.print("Numel, numero 322, Tipo Fuego, Tipo Tierra, hp: 60, ataque: 60, defensa: 40\n");
            case 323 -> System.out.print("Camerupt, numero 323, Tipo Fuego, Tipo Tierra, hp: 70, ataque: 100, defensa: 70\n");
            case 324 -> System.out.print("Torkoal, numero 324, Tipo Fuego, , hp: 70, ataque: 85, defensa: 140\n");
            case 325 -> System.out.print("Spoink, numero 325, Tipo Psíquico, , hp: 60, ataque: 25, defensa: 35\n");
            case 326 -> System.out.print("Grumpig, numero 326, Tipo Psíquico, , hp: 80, ataque: 45, defensa: 65\n");
            case 327 -> System.out.print("Spinda, numero 327, Tipo Normal, , hp: 60, ataque: 60, defensa: 60\n");
            case 328 -> System.out.print("Trapinch, numero 328, Tipo Tierra, , hp: 45, ataque: 100, defensa: 45\n");
            case 329 -> System.out.print("Vibrava, numero 329, Tipo Tierra, Tipo Dragón, hp: 50, ataque: 70, defensa: 50\n");
            case 330 -> System.out.print("Flygon, numero 330, Tipo Tierra, Tipo Dragón, hp: 80, ataque: 100, defensa: 80\n");
            case 331 -> System.out.print("Cacnea, numero 331, Tipo Planta, , hp: 50, ataque: 85, defensa: 40\n");
            case 332 -> System.out.print("Cacturne, numero 332, Tipo Planta, Tipo Siniestro, hp: 70, ataque: 115, defensa: 60\n");
            case 333 -> System.out.print("Swablu, numero 333, Tipo Normal, Tipo Volador, hp: 45, ataque: 40, defensa: 60\n");
            case 334 -> System.out.print("Altaria, numero 334, Tipo Dragón, Tipo Volador, hp: 75, ataque: 70, defensa: 90\n");
            case 335 -> System.out.print("Zangoose, numero 335, Tipo Normal, , hp: 73, ataque: 115, defensa: 60\n");
            case 336 -> System.out.print("Seviper, numero 336, Tipo Veneno, , hp: 73, ataque: 100, defensa: 60\n");
            case 337 -> System.out.print("Lunatone, numero 337, Tipo Roca, Tipo Psíquico, hp: 70, ataque: 55, defensa: 65\n");
            case 338 -> System.out.print("Solrock, numero 338, Tipo Roca, Tipo Psíquico, hp: 70, ataque: 95, defensa: 85\n");
            case 339 -> System.out.print("Barboach, numero 339, Tipo Agua, Tipo Tierra, hp: 50, ataque: 48, defensa: 43\n");
            case 340 -> System.out.print("Whiscash, numero 340, Tipo Agua, Tipo Tierra, hp: 110, ataque: 78, defensa: 73\n");
            case 341 -> System.out.print("Corphish, numero 341, Tipo Agua, , hp: 43, ataque: 80, defensa: 65\n");
            case 342 -> System.out.print("Crawdaunt, numero 342, Tipo Agua, Tipo Siniestro, hp: 63, ataque: 120, defensa: 85\n");
            case 343 -> System.out.print("Baltoy, numero 343, Tipo Tierra, Tipo Psíquico, hp: 40, ataque: 40, defensa: 55\n");
            case 344 -> System.out.print("Claydol, numero 344, Tipo Tierra, Tipo Psíquico, hp: 60, ataque: 70, defensa: 105\n");
            case 345 -> System.out.print("Lileep, numero 345, Tipo Roca, Tipo Planta, hp: 66, ataque: 41, defensa: 77\n");
            case 346 -> System.out.print("Cradily, numero 346, Tipo Roca, Tipo Planta, hp: 86, ataque: 81, defensa: 97\n");
            case 347 -> System.out.print("Anorith, numero 347, Tipo Roca, Tipo Bicho, hp: 45, ataque: 95, defensa: 50\n");
            case 348 -> System.out.print("Armaldo, numero 348, Tipo Roca, Tipo Bicho, hp: 75, ataque: 125, defensa: 100\n");
            case 349 -> System.out.print("Feebas, numero 349, Tipo Agua, , hp: 20, ataque: 15, defensa: 20\n");
            case 350 -> System.out.print("Milotic, numero 350, Tipo Agua, , hp: 95, ataque: 60, defensa: 79\n");
            case 351 -> System.out.print("Castform, numero 351, Tipo Normal, , hp: 70, ataque: 70, defensa: 70\n");
            case 352 -> System.out.print("Kecleon, numero 352, Tipo Normal, , hp: 60, ataque: 90, defensa: 70\n");
            case 353 -> System.out.print("Shuppet, numero 353, Tipo Fantasma, , hp: 44, ataque: 75, defensa: 35\n");
            case 354 -> System.out.print("Banette, numero 354, Tipo Fantasma, , hp: 64, ataque: 115, defensa: 65\n");
            case 355 -> System.out.print("Duskull, numero 355, Tipo Fantasma, , hp: 20, ataque: 40, defensa: 90\n");
            case 356 -> System.out.print("Dusclops, numero 356, Tipo Fantasma, , hp: 40, ataque: 70, defensa: 130\n");
            case 357 -> System.out.print("Tropius, numero 357, Tipo Planta, Tipo Volador, hp: 99, ataque: 68, defensa: 83\n");
            case 358 -> System.out.print("Chimecho, numero 358, Tipo Psíquico, , hp: 65, ataque: 50, defensa: 70\n");
            case 359 -> System.out.print("Absol, numero 359, Tipo Siniestro, , hp: 65, ataque: 130, defensa: 60\n");
            case 360 -> System.out.print("Wynaut, numero 360, Tipo Psíquico, , hp: 95, ataque: 23, defensa: 48\n");
            case 361 -> System.out.print("Snorunt, numero 361, Tipo Hielo, , hp: 50, ataque: 50, defensa: 50\n");
            case 362 -> System.out.print("Glalie, numero 362, Tipo Hielo, , hp: 80, ataque: 80, defensa: 80\n");
            case 363 -> System.out.print("Spheal, numero 363, Tipo Hielo, Tipo Agua, hp: 70, ataque: 40, defensa: 50\n");
            case 364 -> System.out.print("Sealeo, numero 364, Tipo Hielo, Tipo Agua, hp: 90, ataque: 60, defensa: 70\n");
            case 365 -> System.out.print("Walrein, numero 365, Tipo Hielo, Tipo Agua, hp: 110, ataque: 80, defensa: 90\n");
            case 366 -> System.out.print("Clamperl, numero 366, Tipo Agua, , hp: 35, ataque: 64, defensa: 85\n");
            case 367 -> System.out.print("Huntail, numero 367, Tipo Agua, , hp: 55, ataque: 104, defensa: 105\n");
            case 368 -> System.out.print("Gorebyss, numero 368, Tipo Agua, , hp: 55, ataque: 84, defensa: 105\n");
            case 369 -> System.out.print("Relicanth, numero 369, Tipo Agua, Tipo Roca, hp: 100, ataque: 90, defensa: 130\n");
            case 370 -> System.out.print("Luvdisc, numero 370, Tipo Agua, , hp: 43, ataque: 30, defensa: 55\n");
            case 371 -> System.out.print("Bagon, numero 371, Tipo Dragón, , hp: 45, ataque: 75, defensa: 60\n");
            case 372 -> System.out.print("Shelgon, numero 372, Tipo Dragón, , hp: 65, ataque: 95, defensa: 100\n");
            case 373 -> System.out.print("Salamence, numero 373, Tipo Dragón, Tipo Volador, hp: 95, ataque: 135, defensa: 80\n");
            case 374 -> System.out.print("Beldum, numero 374, Tipo Acero, Tipo Psíquico, hp: 40, ataque: 55, defensa: 80\n");
            case 375 -> System.out.print("Metang, numero 375, Tipo Acero, Tipo Psíquico, hp: 60, ataque: 75, defensa: 100\n");
            case 376 -> System.out.print("Metagross, numero 376, Tipo Acero, Tipo Psíquico, hp: 80, ataque: 135, defensa: 130\n");
            case 377 -> System.out.print("Regirock, numero 377, Tipo Roca, , hp: 80, ataque: 100, defensa: 200\n");
            case 378 -> System.out.print("Regice, numero 378, Tipo Hielo, , hp: 80, ataque: 50, defensa: 100\n");
            case 379 -> System.out.print("Registeel, numero 379, Tipo Acero, , hp: 80, ataque: 75, defensa: 150\n");
            case 380 -> System.out.print("Latias, numero 380, Tipo Dragón, Tipo Psíquico, hp: 80, ataque: 80, defensa: 90\n");
            case 381 -> System.out.print("Latios, numero 381, Tipo Dragón, Tipo Psíquico, hp: 80, ataque: 90, defensa: 80\n");
            case 382 -> System.out.print("Kyogre, numero 382, Tipo Agua, , hp: 100, ataque: 100, defensa: 90\n");
            case 383 -> System.out.print("Groudon, numero 383, Tipo Tierra, , hp: 100, ataque: 150, defensa: 140\n");
            case 384 -> System.out.print("Rayquaza, numero 384, Tipo Dragón, Tipo Volador, hp: 105, ataque: 180, defensa: 100\n");
            case 385 -> System.out.print("Jirachi, numero 385, Tipo Acero, Tipo Psíquico, hp: 100, ataque: 100, defensa: 100\n");
            case 386 -> System.out.print("Deoxys, numero 386, Tipo Psíquico, , hp: 50, ataque: 150, defensa: 50\n");

            default -> System.out.println("Fuera de los parametros establecidos para los poekemon");
        }
        System.out.println("Salir preciona -x-");
        x = dex.next();
    } 
    while (!x.equals("x"));
    dex.close();
}
}